In [1]:
import numpy as np

In [46]:
data = np.array([1, 2, 3, 3, 4, 4, 4, 5, 5.5, 6, 6, 6.5, 7, 7, 7.5, 8, 9, 12, 52, 90], dtype=np.float32)

In [47]:
data

array([ 1. ,  2. ,  3. ,  3. ,  4. ,  4. ,  4. ,  5. ,  5.5,  6. ,  6. ,
        6.5,  7. ,  7. ,  7.5,  8. ,  9. , 12. , 52. , 90. ],
      dtype=float32)

In [48]:
mediana = np.median(data)
mediana

6.0

In [49]:
desvios_absolutos = np.abs(data - mediana)
desvios_absolutos

array([ 5. ,  4. ,  3. ,  3. ,  2. ,  2. ,  2. ,  1. ,  0.5,  0. ,  0. ,
        0.5,  1. ,  1. ,  1.5,  2. ,  3. ,  6. , 46. , 84. ],
      dtype=float32)

In [50]:
mad = np.median(desvios_absolutos)
mad

2.0

In [51]:
point_mad = desvios_absolutos / mad
point_mad

array([ 2.5 ,  2.  ,  1.5 ,  1.5 ,  1.  ,  1.  ,  1.  ,  0.5 ,  0.25,
        0.  ,  0.  ,  0.25,  0.5 ,  0.5 ,  0.75,  1.  ,  1.5 ,  3.  ,
       23.  , 42.  ], dtype=float32)

In [52]:
mad_e = 1.4826 * mad
mad_e

2.9652

In [54]:
data[((desvios_absolutos / mad_e) > 2)]

array([12., 52., 90.], dtype=float32)